# Generated by Django 3.2.15 on 2022-09-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220923_0709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
